language: java
jdk:
  - openjdk10
before_install:
  - cd sources
before_script:
  - sleep 5
script:
  - mvn test -B
  - mvn verify -B
after_success:
  - mvn clean cobertura:cobertura coveralls:report
