sudo: required
language: java
jdk:
  - openjdk10
services:
  - elasticsearch
env:
  matrix:
    - ELASTICSEARCH=6.4.2
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH}.deb && sudo dpkg -i --force-confnew elasticsearch-${ELASTICSEARCH}.deb && sudo service elasticsearch restart
  - cd sources
before_script:
  - sleep 10
script:
  - mvn test verify jacoco:report -B
after_success:
  - mvn coveralls:report
