language: java
jdk:
  - openjdk8
services:
  - elasticsearch
# does not support 5.5.x, so see https://docs.travis-ci.com/user/database-setup/#ElasticSearch https://www.peterbe.com/plog/elasticsearch-5-in-travis-ci
env:
  matrix:
    - ELASTICSEARCH=5.5.1
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH}.deb && sudo dpkg -i --force-confnew elasticsearch-${ELASTICSEARCH}.deb && sudo service elasticsearch restart
before_script:
  - sleep 5
