language: java
jdk:
  - openjdk8
services:
  - elasticsearch
# does not support 5.5.x, so see https://docs.travis-ci.com/user/database-setup/#ElasticSearch https://www.peterbe.com/plog/elasticsearch-5-in-travis-ci
env:
  global:
  - ZOOKEEPER_PEERS=localhost:2181
  - KAFKA_PEERS=localhost:9092
  matrix:
  - ELASTICSEARCH=5.5.1
before_install:
# elasticsearch : see https://docs.travis-ci.com/user/database-setup/#ElasticSearch
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH}.deb && sudo dpkg -i --force-confnew elasticsearch-${ELASTICSEARCH}.deb && sudo service elasticsearch restart
# kafka : inspired by https://github.com/wvanbergen/kafka/blob/master/.travis.yml
# TODO LATER rather docker see https://github.com/SOHU-Co/kafka-node/blob/master/.travis.yml ?
  - wget http://www.us.apache.org/dist/kafka/1.0.0/kafka_2.11-1.0.0.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
  - sleep 5
  - kafka/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --topic file --zookeeper localhost:2181
before_script:
  - sleep 5
script:
  - mvn test -B
  - mvn verify -B
after_success:
  - mvn clean cobertura:cobertura coveralls:report
