- name: stop service zookeeper
  service:
    name: zookeeper.service
    daemon_reload: yes
    state: stopped

- name: Clean zookeeper files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ pcu_defaults.zookeeper3.service_folder }}/zookeeper.service"
    - "/etc/init.d/zookeeper"
    - "{{ pcu_defaults.zookeeper3.remote_folder }}/"
    - "{{ pcu_defaults.zookeeper3.conf_file.dataDir }}"
    - "/var/log/zookeeper"

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes
