- name: check if zookeeper service exists
  stat:
    path: "{{ pcu_defaults.zookeeper3.service_folder }}/zookeeper.service"
  register: st

- name: debug
  debug:
    msg: "zookeeper service must be stopped"
  when: st.stat.exists

- name: stop service zookeeper
  service:
    name: zookeeper.service
    daemon_reload: yes
    state: stopped
  when: st.stat.exists

- name: Clean zookeeper files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ pcu_defaults.zookeeper3.service_folder }}/zookeeper.service"
    - "{{ pcu_defaults.zookeeper3.remote_folder }}/"
    - "{{ pcu_defaults.zookeeper3.conf_file.dataDir }}"
    - "/var/log/zookeeper"

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes
