# (defaults are commented out)
spring:
    #profiles.active: staging

security:
  user:
    password: password

pcu:
  #devmode: true
  entreprisesearch:
  connector:
    runAtStartup: true
    # every night at 3 AM
    cron: 0 0 3 * * *
  search:
    es:
      client:
         #address: http://localhost:9200/
      #restLogFile: es-rest-mock.log
      restLogFile: 
  file:
    local:
      storeRootPath: ./pcu_store
  providers:
  - org.pcu.providers.search.elasticsearch.spi
  - org.pcu.providers.file.local.spi
  rest:
    #failOnUnknownProperties: true
    #enableIndenting: false

---
spring:
    profiles: test
pcu:
  connector:
    runAtStartup: false
  file:
    local:
      storeRootPath: /tmp/pcu_store
