- name: Add the 'pcu_user'
  user:
    name: "{{ pcu_defaults.pcu_user }}"
    comment: pcu user

- name: Download jdk10
  local_action: get_url url={{ pcu_defaults.jdk10.url }} dest={{ pcu_defaults.download_folder }}/{{ pcu_defaults.jdk10.name }} checksum={{ pcu_defaults.jdk10.checksum }}
  #https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz.sha256

- name: creating jvm directory
  file:
    path: /usr/lib/jvm
    state: directory

- name: unarchive jdk10
  unarchive:
    src: /tmp/openjdk-10.0.2_linux-x64_bin.tar.gz
    creates: "{{ pcu_defaults.jdk10.java_home }}"
    dest: /usr/lib/jvm/

- name: adding alternatives java
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ pcu_defaults.jdk10.java_home }}/bin/java"
    priority: 1

- name: adding alternatives javac
  alternatives:
    name: javac
    link: /usr/bin/javac
    path: "{{ pcu_defaults.jdk10.java_home }}/bin/javac"
    priority: 1
