# (defaults are commented out)

application:
  entreprisesearch:

pcu:
  search:
    api:
      client:
         # address: http://localhost:8080/
      # restLogFile: es-rest-mock.log
      restLogFile: 
  rest:
    # enableIndenting: true
