DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST ( ID VARCHAR(255), TITLE VARCHAR(255), DESCRIPTION VARCHAR(255));
INSERT INTO TEST(ID,TITLE,DESCRIPTION) VALUES ('ID1', 'TITLE1','DESCRIPTION1');
INSERT INTO TEST(ID,TITLE,DESCRIPTION) VALUES ('ID2', 'TITLE2','DESCRIPTION2');
INSERT INTO TEST(ID,TITLE,DESCRIPTION) VALUES ('ID3', 'TITLE3','DESCRIPTION3');
